
package browser;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 * @author Alec Hewitt C0704504
 */
public class MainFrame extends javax.swing.JFrame {

    private static JSplitPane  splitPane;
    public static TabbedPanel currentTabbedPanel;
    private static DatabaseConection database;
    private static TabbedPanel tabPanel1;
    private static TabbedPanel tabPanel2;


    public MainFrame() {
        
        //Initilise database for bookmarks and history
        database = new DatabaseConection("historyAndFavourites.db");
        
        //Initialise netbeans generated components
        initComponents();

        tabPanel1 = new TabbedPanel();
        tabPanel1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFrame.setCurrentTabbedPanel(tabPanel1);
          }
        });

        setCurrentTabbedPanel(tabPanel1);
        getContentPane().add(tabPanel1, java.awt.BorderLayout.CENTER);
        this.setTitle("Alec's Web Browser");

        
        
    }

    
    public static void setCurrentTabbedPanel(TabbedPanel tabbedPanel){
        currentTabbedPanel = tabbedPanel;
        currentTabbedPanel.updateCloseButtons();
    }
    
    /** Code generated by Netbeans ide.*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        closeTabFile = new javax.swing.JMenuItem();
        newTabFile = new javax.swing.JMenuItem();
        openFileMenu = new javax.swing.JMenuItem();
        saveFileMenu = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        viewLayoutMenu = new javax.swing.JMenu();
        layoutSingleMenuItem = new javax.swing.JMenuItem();
        layout2ColumnsMenuItem = new javax.swing.JMenuItem();
        viewBookmarkMenu = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        menuFile.setText("File");

        closeTabFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        closeTabFile.setText("Close current Tab");
        closeTabFile.setEnabled(false);
        closeTabFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTabFileActionPerformed(evt);
            }
        });
        menuFile.add(closeTabFile);

        newTabFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newTabFile.setText("New Tab");
        newTabFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTabFileActionPerformed(evt);
            }
        });
        menuFile.add(newTabFile);

        openFileMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFileMenu.setText("Open");
        openFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuActionPerformed(evt);
            }
        });
        menuFile.add(openFileMenu);

        saveFileMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveFileMenu.setText("Save Page");
        saveFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileMenuActionPerformed(evt);
            }
        });
        menuFile.add(saveFileMenu);

        mainMenuBar.add(menuFile);

        menuView.setText("View");

        viewLayoutMenu.setText("Layout");

        layoutSingleMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        layoutSingleMenuItem.setText("Single");
        layoutSingleMenuItem.setEnabled(false);
        layoutSingleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutSingleMenuItemActionPerformed(evt);
            }
        });
        viewLayoutMenu.add(layoutSingleMenuItem);

        layout2ColumnsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        layout2ColumnsMenuItem.setText("2 Columns");
        layout2ColumnsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layout2ColumnsMenuItemActionPerformed(evt);
            }
        });
        viewLayoutMenu.add(layout2ColumnsMenuItem);

        menuView.add(viewLayoutMenu);

        viewBookmarkMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        viewBookmarkMenu.setText("Bookmarks");
        viewBookmarkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookmarkMenuActionPerformed(evt);
            }
        });
        menuView.add(viewBookmarkMenu);

        mainMenuBar.add(menuView);

        menuHelp.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuHelp.add(jMenuItem1);

        mainMenuBar.add(menuHelp);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void closeTabFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTabFileActionPerformed
        currentTabbedPanel.closeTab();
        currentTabbedPanel.updateCloseButtons();   
    }//GEN-LAST:event_closeTabFileActionPerformed

    
    //Change to single column mode.
    private void layoutSingleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layoutSingleMenuItemActionPerformed
             
        //Enable 2 columns menu item, Disable Single column menu item
        layout2ColumnsMenuItem.setEnabled(true);
        layoutSingleMenuItem.setEnabled(false);
        
        //deleate last tab of tabPanel1
        int indexLast = tabPanel1.allTabs.size() -1;
        //tabPanel1.remove( tabPanel1.allTabs.get(indexLast) );
        tabPanel1.allTabs.remove(indexLast);
        
        //add tabs from tabPanel2 into tabPanel1 tab array.
        for (Tab tab : tabPanel2.allTabs){
            tabPanel1.allTabs.add(tab);
        }
        
        tabPanel1.removeAll();
        
        int i = 1;
        for(Tab tab: tabPanel1.allTabs){
            if( i == tabPanel1.allTabs.size()){
                //Adding blank listening tab
                tabPanel1.addTab("", tab);
                
            }
            else{
                //Adding all other Tabs from tabPanel1's array
                tabPanel1.addTab(null, tab);
                tabPanel1.setTabTitle(tab);
                
            }
            i++;
            
        }
       //Remove splitPane
        remove(splitPane);
        
        //Add tabPanel1
        getContentPane().add(tabPanel1, java.awt.BorderLayout.CENTER);
        
        this.validate();
        this.repaint();
        
        
    }//GEN-LAST:event_layoutSingleMenuItemActionPerformed

    //Create 2 column split pane.
    private void layout2ColumnsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layout2ColumnsMenuItemActionPerformed
        
        //disable 2 columns menu item, Enable Single column menu item
        layout2ColumnsMenuItem.setEnabled(false);
        layoutSingleMenuItem.setEnabled(true);
                
        //remove single JTabbedPane
        remove(tabPanel1);
        
        //Create a new TabbedPanel
        tabPanel2 = new TabbedPanel();
        MainFrame.setCurrentTabbedPanel(tabPanel2);
        tabPanel2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFrame.setCurrentTabbedPanel(tabPanel2);
           }
         });
       
        //Create a split pane with the two Tabbed panels in it.
        splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, tabPanel1, tabPanel2);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(300);

        //Provide minimum sizes for the two components in the split pane
        Dimension minimumSize = new Dimension(100, 50);
        tabPanel1.setMinimumSize(minimumSize);
        tabPanel2.setMinimumSize(minimumSize);
        
        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);
        this.validate();
        this.repaint();
        
        
    }//GEN-LAST:event_layout2ColumnsMenuItemActionPerformed

    private void newTabFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTabFileActionPerformed
        //add a new tab to the currently selected tabbed panel
        currentTabbedPanel.addNewTab();
        
        //Add the tab to the tabs panel array list
        int indexNew = currentTabbedPanel.allTabs.size() - 2;
        currentTabbedPanel.setSelectedIndex(indexNew);
        
        //Enable the close tab button on the file menu - there will now be more than 2 tabs
        closeTabFile.setEnabled(true);
    
    }//GEN-LAST:event_newTabFileActionPerformed

    private void openFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File webpage = chooser.getSelectedFile();
        try{
            URL url;
            url= webpage.toURL();
            Tab selectedTab = currentTabbedPanel.getSelectedTab();
            selectedTab.setURL(url);
        }
        catch (MalformedURLException e){
            System.out.println("File doesn't exist " + e);
        }
        catch( NullPointerException e){
            System.out.println("No file was selected " + e);
        }
        
        
    }//GEN-LAST:event_openFileMenuActionPerformed

    private void saveFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileMenuActionPerformed
        SavePage saveCurrent = new SavePage(currentTabbedPanel);    
    }//GEN-LAST:event_saveFileMenuActionPerformed

    private void viewBookmarkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookmarkMenuActionPerformed
        FavouritesFrame favourites = new FavouritesFrame();
        favourites.setVisible(true);
    }//GEN-LAST:event_viewBookmarkMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this,
        "Alec's Browser:\n"
                + "Created by Alexander Hewitt -  C0704504\n"
                + "For CMT205 Object-Oriented Development with Java",
        "About Alec's Browser",
        JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public static TabbedPanel getTabPanel1(){
        return tabPanel1;
    }
    
    public static TabbedPanel getTabPanel2(){
        return tabPanel2;
    }
    
    public static TabbedPanel getCurrentTabbedPanel(){
        return currentTabbedPanel;
    }
    
    public static DatabaseConection getDatabase(){
        return database;
    }
    
    //Main method generated by netbeans.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    //Variables created by Netbeans
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem closeTabFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem layout2ColumnsMenuItem;
    private javax.swing.JMenuItem layoutSingleMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem newTabFile;
    private javax.swing.JMenuItem openFileMenu;
    private javax.swing.JMenuItem saveFileMenu;
    private javax.swing.JMenuItem viewBookmarkMenu;
    private javax.swing.JMenu viewLayoutMenu;
    // End of variables declaration//GEN-END:variables
}
